apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rmq-scaledobj
spec:
  scaleTargetRef:
    name:           nginx-deployment                       # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval:  4                                      # Optional. Default: 30 seconds
  cooldownPeriod:   100                                     # Optional. Default: 300 seconds
  idleReplicaCount: 0                                       # Optional. Default: ignored, must be less than minReplicaCount 
  minReplicaCount:  1                                       # Optional. Default: 0
  maxReplicaCount:  10                                     # Optional. Default: 100
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672 # Optional. If not specified, it must be done by using TriggerAuthentication.
      protocol: auto # Optional. Specifies protocol to use, either amqp or http, or auto to autodetect based on the `host` value. Default value is auto.
      mode: QueueLength # QueueLength or MessageRate
      value: "4" # message backlog or publish/sec. target per instance
      queueName: TestQueue
      unsafeSsl: "true"